<a href="https://colab.research.google.com/github/sabumjung/Pytorch/blob/master/gradient_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.ones(10)
b=np.ones(10)*2
c=b*a
d=c+1

In [0]:
a=torch.Tensor([1,0])


In [19]:
import torch
from torch.autograd import Variable
from datetime import datetime
start=datetime.now()

N,D=3,4

x=Variable(torch.randn(N,D).cuda(), requires_grad=True)
y=Variable(torch.randn(N,D).cuda(), requires_grad=True)
z=Variable(torch.randn(N,D).cuda(), requires_grad=True)

a=x*y
b=a+z
c=torch.sum(b)

# c.backward()
c.backward()

print(x.grad)
print(y.grad)
print(z.grad)
print(datetime.now()-start)

tensor([[-1.5325, -0.6167, -0.2168,  0.7045],
        [-0.5803, -0.4136,  0.7429, -0.3038],
        [ 1.5163, -1.2448, -1.1481,  0.1926]], device='cuda:0')
tensor([[ 0.1713, -0.5186,  1.8024, -0.6330],
        [-0.2922, -0.4246,  0.4898, -0.0809],
        [ 0.4006,  0.8225,  1.1086,  1.5215]], device='cuda:0')
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
0:00:00.008046


In [4]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

tcmalloc: large alloc 1073750016 bytes == 0x5577c7690000 @  0x7f2e4dffe2a4 0x55776f19ab68 0x55776f28692d 0x55776f1ae01a 0x55776f1b2d72 0x55776f1ab8ca 0x55776f1b324e 0x55776f1ab8ca 0x55776f1b324e 0x55776f1ab8ca 0x55776f1b324e 0x55776f1ab8ca 0x55776f1b37d3 0x55776f1ab8ca 0x55776f1b324e 0x55776f1ab8ca 0x55776f1b324e 0x55776f1b2d72 0x55776f1b2d72 0x55776f1ab8ca 0x55776f1b37d3 0x55776f1b2d72 0x55776f1ab8ca 0x55776f1b37d3 0x55776f1ab8ca 0x55776f1b37d3 0x55776f1ab8ca 0x55776f1b324e 0x55776f1ab8ca 0x55776f1ab1e9 0x55776f1dbbdf


In [0]:
import torch
from torch.autograd import Variable

In [21]:
x=Variable(torch.ones(2,2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [22]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [23]:
print(y.grad_fn)

In [28]:
z=y*y*3
out=z.mean()
out1=z.std()

print(z)
print("---"*5)
print(out)
print("---"*5)
print(out1)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)
---------------
tensor(27., grad_fn=<MeanBackward1>)
---------------
tensor(0., grad_fn=<StdBackward0>)


In [25]:
print(y.grad_fn)

In [29]:
print(out.backward())

None


In [31]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
x=torch.randn(3)
x=Variable(x, requires_grad=True)
print(x)


tensor([ 0.2183, -0.2365, -1.4999], requires_grad=True)


In [36]:
y=x*2
print(y)

while y.data.norm()<1000:
  y=y*2
print(y)

tensor([ 0.4366, -0.4729, -2.9999], grad_fn=<MulBackward>)
tensor([  223.5169,  -242.1406, -1535.9453], grad_fn=<MulBackward>)


In [38]:
gradients=torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
print(x.grad)


tensor([ 102.4000, 1024.0000,    0.1024])
